Repository rexray/rexray, pull requests merged in 2018-05, with the labels that each got.

#1139 Restore missing doc entries
  .docs/user-guide/storage-providers/ceph.md
  .docs/user-guide/storage-providers/microsoft.md
  .docs/user-guide/storage-providers/openstack.md
Labels: azure, documentation, openstack, rbd

#1226 Enable Docker Legacy Mode by Default
  core/core.go
Labels: feature request

#1080 Add support for custom CA certificate and insecure mode
  libstorage/drivers/storage/cinder/cinder.go
  libstorage/drivers/storage/cinder/storage/cinder_storage.go
Labels: enhancement, openstack
